# Configuration used by the Supabase CLI for linting and database migrations.
# Replace `your-project-ref` with the unique reference of your Supabase project.
project_id = "myclosetb"

[project]
ref = "your-project-ref"
api_url = "https://api.supabase.com"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54323
major_version = 15
shadow_database_url = ""

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[storage]
file_size_limit = "50MiB"

[migrations]
# Folder that stores SQL migrations checked into the repository.
path = "supabase/migrations"
