version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile
    env_file:
      - ../.env.example
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
    environment:
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN:-}
      - VITE_METRICS_ENDPOINT=${VITE_METRICS_ENDPOINT:-http://backend:8000/metrics}
    ports:
      - "3000:80"
    depends_on:
      - backend
