name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend quality gates
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: backend/pyproject.toml
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Lint
        run: ruff check src tests
      - name: Static Application Security Testing
        run: bandit -r src/myclosetb_backend -ll
      - name: Run tests with coverage
        run: coverage run -m pytest
      - name: Coverage report
        run: coverage report
      - name: Build distribution
        run: python -m build

  frontend:
    name: Frontend quality gates
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package.json
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Static Application Security Testing
        run: npm run sast
      - name: Run unit tests
        run: npm run test
      - name: Run tests with coverage
        run: npm run coverage
      - name: Build
        run: npm run build

  supabase:
    name: Supabase schema lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Lint database migrations
        run: supabase db lint
